package com.jbpm_tests.usertaskassignmentdrl;

import java.util.HashMap;

import org.kie.internal.task.api.assignment.Assignment;
import org.kie.api.task.model.Task;
import org.kie.api.task.model.TaskData;
import org.kie.api.task.model.PeopleAssignments;

import org.jbpm.services.task.impl.model.*;


rule "Standard loan amount rule"
    when
        $inputParameters : HashMap($inputParameters.containsKey("amount"))
        eval(((String)$inputParameters.get("taskName")).equals("First User Task"))
        eval((int)$inputParameters.get("amount") < 1000)
    then
        System.out.println("Rule 0: Standard loan amount rule");
        insert(new String("STANDARD_LOAN_GRANTING"));
end


rule "High loan amount rule"
    when
        $inputParameters : HashMap($inputParameters.containsKey("amount"))
        eval(((String)$inputParameters.get("taskName")).equals("First User Task"))
        eval((int)$inputParameters.get("amount") >= 1000)
    then
        System.out.println("Rule 1: High loan amount rule");
        insert(new String("HIGH_AMOUNT_LOAN_GRANTING"));
end